const populationSimulation = require('./index')
console.log('Single', populationSimulation.singleGeneration())
console.log('Multi', populationSimulation.multiGeneration())
console.log('Dynamic', populationSimulation.dynamicGeneration())
console.log('Nonequi', populationSimulation.nonEquilibrium())